ci:
    # collect options here
    collect:
        staticDistDir: "dist/"
        url:
            - http://localhost/
            # - http://localhost/101-qr-code-component
            # - http://localhost/102-nft-preview-card-component
            # - http://localhost/103-order-summary-component
            # - http://localhost/104-stats-preview-card-component
            # - http://localhost/105-3-column-preview-card-component
            # - http://localhost/106-profile-card-component
            # - http://localhost/107-faq-accordion-card
            # - http://localhost/108-social-proof-section
            # - http://localhost/109-article-preview-component
            # - http://localhost/110-four-card-feature-section
            # - http://localhost/111-base-apparel-coming-soon
            # - http://localhost/112-intro-component-with-signup-form
            # - http://localhost/113-single-price-grid-component
            # - http://localhost/114-ping-coming-soon-page
            # - http://localhost/115-huddle-landing-page-with-single-introductory-section
            # - http://localhost/201-time-tracking-dashboard
            # - http://localhost/202-tip-calculator-app
            # - http://localhost/203-sunnyside-agency-landing-page
            # - http://localhost/204-blogr-landing-page
            # - http://localhost/205-crowdfunding-product-page
            # - http://localhost/206-interactive-pricing-component
            # - http://localhost/207-loopstudios-landing-page
            # - http://localhost/208-testimonials-grid-section
            # - http://localhost/209-fylo-data-storage-component
            # - http://localhost/200-coding-bootcamp-testimonials-slider
            # - http://localhost/211-social-media-dashboard-with-theme-switcher
            # - http://localhost/212-insure-landing-page
            # - http://localhost/213-pricing-component-with-toggle
            # - http://localhost/214-project-tracking-intro-component
            # - http://localhost/215-clipboard-landing-page
            # - http://localhost/216-huddle-landing-page-with-alternating-feature-blocks
            # - http://localhost/217-fylo-dark-theme-landing-page
            # - http://localhost/218-fylo-landing-page-with-two-column-layout
            # - http://localhost/219-huddle-landing-page-with-curved-sections
            # - http://localhost/301-interactive-comments-section
            # - http://localhost/302-ecommerce-product-page
            # - http://localhost/303-calculator-app
            # - http://localhost/304-launch-countdown-timer
            # - http://localhost/305-todo-app
            # - http://localhost/306-room-homepage
            # - http://localhost/307-ip-address-tracker
            # - http://localhost/308-chat-app-css-illustration
            # - http://localhost/309-static-job-listings
            # - http://localhost/300-easybank-landing-page
            # - http://localhost/311-manage-landing-page
            # - http://localhost/312-url-shortening-api
            # - http://localhost/313-bookmark-landing-page
            # - http://localhost/314-rock-paper-scissors
            # - http://localhost/315-rest-countries-api-with-color-theme-switcher
            # - http://localhost/316-space-tourism-website

    assert:
        # assert options here

    upload:
        # upload options here
        # target: "temporary-public-storage"
        # target: "lhci"
        target: "filesystem"
        outputDir: "./.lhci"
    server:
        # server options here

    wizard:
        # wizard options here
