on:
  push:
    branches: [main]
    paths: ["docs/**", ".github/workflows/docs.yml"]

jobs:
  generate_readme:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - run: pnpm install
      - run: |
          git config user.name  "Github Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Generate README
        run: ./scripts/gen_readme.sh
