on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["src/**", ".github/workflows/lint.yml"]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - run: pnpm install
      - run: make fmt-check
      - run: make lint-css
